apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: httpserver01
  labels:
    app.kubernetes.io/instance: httpserver01
    app.kubernetes.io/managed-by: crd
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: httpserver01
  template:
    template:
    metadata:
      labels:
        app.kubernetes.io/instance: httpserver01
    spec:
      containers:
      - args:
        - -c
        - /app/server -conf /app/config.json
        command:
        - /bin/sh
        image: faisal0097/experiments:1.0.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: httpserver
        ports:
        - containerPort: 3333
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
