# permissions for end users to edit empmanagers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: empmanager-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: httpserver
    app.kubernetes.io/part-of: httpserver
    app.kubernetes.io/managed-by: kustomize
  name: empmanager-editor-role
rules:
- apiGroups:
  - httpserver.ext-k8s.faisal097.com
  resources:
  - empmanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - httpserver.ext-k8s.faisal097.com
  resources:
  - empmanagers/status
  verbs:
  - get
