---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - httpserver.ext-k8s.faisal097.com
  resources:
  - empmanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - httpserver.ext-k8s.faisal097.com
  resources:
  - empmanagers/finalizers
  verbs:
  - update
- apiGroups:
  - httpserver.ext-k8s.faisal097.com
  resources:
  - empmanagers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - httpserver.ext-k8s.faisal097.com
  resources:
  - events
  verbs:
  - create
  - patch
